services:
  msst:
    image: msst-ui:latest
    build: . 
    restart: always
    ports:
      - 8662:7860
    volumes:
      - ./root:/root
      - /TTD-Data/msst/data:/app/data
      - /TTD-Data/msst/pretrain/All_Models:/app/pretrain
      - /TTD:/TTD  # 挂载整个TTD目录以支持项目级处理
    container_name: msst
    environment:
      - LANG=zh_CN.UTF-8
      - LANGUAGE=zh_CN.UTF-8
      - LC_ALL=zh_CN.UTF-8
      - TZ=Asia/Shanghai
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "2" ]
              capabilities: [gpu]
    tty: true
    stdin_open: true
    networks:
      - caddy
    labels:
      caddy: "http://msst"
      caddy.reverse_proxy: "{{upstreams 7860}}"

networks:
  caddy:
    external: true