services:
  msst:
    image: msst-webui/msst:unbuilt
    restart: always
    pids_limit: 200
    cpus: "12.0"
    mem_limit: 64g
    ports:
      - "8662:7860"
    volumes:
      - /opt/msst-webui/root:/root
      - /TTD-Data/msst/data:/app/data
      - /TTD-Data/msst/pretrain/All_Models:/app/pretrain
      - /TTD:/TTD
    container_name: msst
    environment:
      LANG: zh_CN.UTF-8
      LANGUAGE: zh_CN.UTF-8
      LC_ALL: zh_CN.UTF-8
      TZ: Asia/Shanghai
      OPENBLAS_NUM_THREADS: "1"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2"]
              capabilities: [gpu]
    tty: true
    stdin_open: true
    networks:
      - caddy
    labels:
      caddy: "http://msst"
      caddy.reverse_proxy: "{{upstreams 7860}}"

networks:
  caddy:
    external: true
